# Google Cloud Build Configuration for Mindweave
# Builds and deploys to Cloud Run
#
# Required substitutions:
#   _SERVICE_NAME: Name of the Cloud Run service (e.g., mindweave-prod)
#   _REGION: GCP region (e.g., us-central1)
#   _DATABASE_URL: Cloud SQL connection string
#
# Secrets (stored in Secret Manager):
#   - google-ai-api-key (Gemini AI)
#   - auth-secret
#   - google-oauth-client-id (optional)
#   - google-oauth-client-secret (optional)

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--build-arg'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=${_APP_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_TURNSTILE_SITE_KEY=0x4AAAAAACa3eqmrh0p5DsBc'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production,NEXT_PUBLIC_APP_URL=${_APP_URL},AUTH_URL=${_APP_URL},CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_INSTANCE},NEXT_PUBLIC_TURNSTILE_SITE_KEY=0x4AAAAAACa3eqmrh0p5DsBc'
      - '--add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets=DATABASE_URL=database-url:latest,GOOGLE_AI_API_KEY=google-ai-api-key:latest,AUTH_SECRET=auth-secret:latest,AUTH_GOOGLE_ID=google-oauth-client-id:latest,AUTH_GOOGLE_SECRET=google-oauth-client-secret:latest,RESEND_API_KEY=resend-api-key:latest,TURNSTILE_SECRET_KEY=turnstile-secret-key:latest'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--port=3000'
    waitFor: ['push-image']

# Timeout for the entire build
timeout: '1800s'

# Substitutions (can be overridden in trigger or gcloud command)
substitutions:
  _SERVICE_NAME: 'mindweave'
  _REGION: 'us-central1'
  _DATABASE_URL: 'postgresql://user:password@host:5432/db'
  _APP_URL: 'https://mindweave.space'
  _CLOUD_SQL_INSTANCE: 'mindweave-prod:us-central1:mindweave-db'

# Images to be pushed to GCR
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  # Use default machine (cost-effective for ~4min builds)
  # Upgrade to E2_HIGHCPU_8 only if builds exceed 10 minutes
  machineType: 'E2_MEDIUM'

  # Enable Docker layer caching
  substitutionOption: 'ALLOW_LOOSE'

  # Enable build logging
  logging: CLOUD_LOGGING_ONLY
