import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Collections',
  description: 'Organize your content into curated collections in Mindweave.',
};

export default function CollectionsPage() {
  return (
    <div className="space-y-8">
      <section>
        <h1 className="text-4xl font-bold mb-3">Collections</h1>
        <p className="text-lg text-muted-foreground leading-relaxed">
          Collections let you group related content into curated bundles for easy access
          and organization. Unlike tags, which categorize individual items, collections
          create meaningful groupings of multiple pieces of content.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Creating a Collection</h2>
        <p className="text-muted-foreground leading-relaxed">
          To create a new collection:
        </p>
        <ol className="list-decimal pl-6 space-y-2 text-muted-foreground">
          <li>Navigate to the <strong>Library</strong> in your dashboard.</li>
          <li>Click <strong>New Collection</strong>.</li>
          <li>Give your collection a descriptive name.</li>
          <li>Optionally add a description to explain the collection&apos;s purpose.</li>
          <li>Click <strong>Create</strong> to save the collection.</li>
        </ol>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Adding Content to Collections</h2>
        <p className="text-muted-foreground leading-relaxed">
          There are several ways to add content to a collection:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
          <li>
            <strong>From a content card</strong> — Use the actions menu on any content card
            to add it to one or more collections.
          </li>
          <li>
            <strong>Bulk select</strong> — Select multiple items in the library and add them
            to a collection at once.
          </li>
          <li>
            <strong>During capture</strong> — When creating new content, you can assign it
            to an existing collection right away.
          </li>
        </ul>
        <p className="text-muted-foreground leading-relaxed">
          A single piece of content can belong to multiple collections simultaneously.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Managing Collections</h2>
        <p className="text-muted-foreground leading-relaxed">
          You can manage your collections from the library:
        </p>
        <ul className="list-disc pl-6 space-y-1 text-muted-foreground">
          <li><strong>Rename</strong> — Edit the collection name and description at any time.</li>
          <li><strong>Remove items</strong> — Remove individual content from a collection without deleting it.</li>
          <li><strong>Delete</strong> — Delete a collection. The content within it remains in your library.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Collections vs. Tags</h2>
        <p className="text-muted-foreground leading-relaxed">
          Both collections and tags help organize content, but they serve different purposes:
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-muted-foreground">
            <thead>
              <tr className="border-b">
                <th className="py-2 pr-4 text-left font-semibold text-foreground">Feature</th>
                <th className="py-2 pr-4 text-left font-semibold text-foreground">Tags</th>
                <th className="py-2 text-left font-semibold text-foreground">Collections</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b">
                <td className="py-2 pr-4">Purpose</td>
                <td className="py-2 pr-4">Categorize individual items</td>
                <td className="py-2">Group related content together</td>
              </tr>
              <tr className="border-b">
                <td className="py-2 pr-4">AI support</td>
                <td className="py-2 pr-4">Auto-generated by Gemini</td>
                <td className="py-2">Manual only</td>
              </tr>
              <tr className="border-b">
                <td className="py-2 pr-4">Best for</td>
                <td className="py-2 pr-4">Topic classification</td>
                <td className="py-2">Project or theme groupings</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Search integration</td>
                <td className="py-2 pr-4">Keyword and semantic</td>
                <td className="py-2">Filter by collection</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Use Case Ideas</h2>
        <ul className="list-disc pl-6 space-y-1 text-muted-foreground">
          <li><strong>Project research</strong> — Group all notes, links, and files for a specific project.</li>
          <li><strong>Learning paths</strong> — Collect resources for learning a new topic.</li>
          <li><strong>Reference materials</strong> — Keep frequently accessed content together.</li>
          <li><strong>Meeting notes</strong> — Bundle notes from a recurring meeting series.</li>
        </ul>
      </section>
    </div>
  );
}
